name: nubank_challenge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: 4.0.0
  flutter:
    sdk: flutter
  get: 4.6.1
  mocktail: ">=0.0.0 <1.0.0"
  dartz: 0.10.0-nullsafety.1
  equatable: ">=2.0.0 <3.0.0"
  cupertino_icons: 1.0.2
  shimmer: 2.0.0
  hive: 2.0.5
  hive_flutter: 1.1.0

dev_dependencies:
  pedantic: 1.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true